name: Test action

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Build
        run: |
          npm ci
          npm run build:test
      - name: Test prometheus
        run: GITHUB_WORKFLOW=workflow GITHUB_JOB=job INPUT_PUSHGATEWAY='http://localhost:9091' INPUT_GATEWAYTYPE=prometheus node test/index.js
      - name: Test zapier
        run: GITHUB_WORKFLOW=workflow GITHUB_JOB=job INPUT_PUSHGATEWAY='http://localhost' node test/index.js
      - name: Test gravel
        run: GITHUB_WORKFLOW=workflow GITHUB_JOB=job INPUT_PUSHGATEWAY='http://localhost:4278' INPUT_GATEWAYTYPE=gravel node test/index.js
